-- Read-only PR Track -> PodorukunSI sync support.
-- Superseded by staging/sync.sql. Never run this incompatible migration.
DO $$ BEGIN RAISE EXCEPTION 'Use the guarded staging/migrate.js on a sanitized copy'; END $$;
--
-- SAFETY: run only against a separately verified staging/development database.
-- This migration is intentionally not executed by this change.

ALTER TABLE IF EXISTS public.companies ADD COLUMN IF NOT EXISTS sync_version bigint NOT NULL DEFAULT 0;
ALTER TABLE IF EXISTS public.projects ADD COLUMN IF NOT EXISTS sync_version bigint NOT NULL DEFAULT 0;
ALTER TABLE IF EXISTS public.clusters ADD COLUMN IF NOT EXISTS sync_version bigint NOT NULL DEFAULT 0;
ALTER TABLE IF EXISTS public.units ADD COLUMN IF NOT EXISTS sync_version bigint NOT NULL DEFAULT 0;
ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS sync_version bigint NOT NULL DEFAULT 0;
ALTER TABLE IF EXISTS public.property_assignments ADD COLUMN IF NOT EXISTS sync_version bigint NOT NULL DEFAULT 0;
ALTER TABLE IF EXISTS public.payment_history ADD COLUMN IF NOT EXISTS sync_version bigint NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS public.sync_outbox (
    seq         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity      text NOT NULL,
    entity_id   uuid NOT NULL,
    operation   text NOT NULL CHECK (operation IN ('insert', 'update', 'delete')),
    occurred_at timestamp with time zone NOT NULL DEFAULT now(),
    payload     jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS sync_outbox_seq_idx ON public.sync_outbox (seq);
CREATE INDEX IF NOT EXISTS sync_outbox_entity_id_idx ON public.sync_outbox (entity, entity_id, seq);

CREATE OR REPLACE FUNCTION public.sync_bump_version()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.sync_version := 1;
    ELSE
        NEW.sync_version := COALESCE(OLD.sync_version, 0) + 1;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.sync_business_payload(p_entity text, p_row jsonb)
RETURNS jsonb
LANGUAGE plpgsql
IMMUTABLE
AS $$
BEGIN
    RETURN CASE p_entity
        WHEN 'companies' THEN jsonb_build_object('id', p_row->'id', 'nama_pt', p_row->'nama_pt', 'kode_pt', p_row->'kode_pt', 'alamat', p_row->'alamat', 'logo_url', p_row->'logo_url', 'theme_color', p_row->'theme_color', 'created_at', p_row->'created_at', 'updated_at', p_row->'updated_at')
        WHEN 'projects' THEN jsonb_build_object('id', p_row->'id', 'company_id', p_row->'company_id', 'nama_proyek', p_row->'nama_proyek', 'deskripsi', p_row->'deskripsi', 'lokasi', p_row->'lokasi', 'status', p_row->'status', 'created_by', p_row->'created_by', 'logo_url', p_row->'logo_url', 'theme_color', p_row->'theme_color', 'created_at', p_row->'created_at', 'updated_at', p_row->'updated_at')
        WHEN 'clusters' THEN jsonb_build_object('id', p_row->'id', 'project_id', p_row->'project_id', 'nama_cluster', p_row->'nama_cluster', 'jumlah_unit', p_row->'jumlah_unit', 'created_at', p_row->'created_at', 'updated_at', p_row->'updated_at')
        WHEN 'units' THEN jsonb_build_object('id', p_row->'id', 'cluster_id', p_row->'cluster_id', 'nomor_unit', p_row->'nomor_unit', 'tipe_rumah', p_row->'tipe_rumah', 'luas_tanah', p_row->'luas_tanah', 'luas_bangunan', p_row->'luas_bangunan', 'status_pembangunan', p_row->'status_pembangunan', 'progress_percentage', p_row->'progress_percentage', 'image_url', p_row->'image_url', 'created_at', p_row->'created_at', 'updated_at', p_row->'updated_at')
        WHEN 'customers' THEN jsonb_build_object('id', p_row->'id', 'company_id', p_row->'company_id', 'nama', p_row->'nama', 'email', p_row->'email', 'nomor_telepon', p_row->'nomor_telepon', 'role', p_row->'role', 'status', p_row->'status', 'created_at', p_row->'created_at', 'updated_at', p_row->'updated_at')
        WHEN 'assignments' THEN jsonb_build_object('id', p_row->'id', 'user_id', p_row->'user_id', 'unit_id', p_row->'unit_id', 'tanggal_pembelian', p_row->'tanggal_pembelian', 'status_kepemilikan', p_row->'status_kepemilikan', 'tipe_pembayaran', p_row->'tipe_pembayaran', 'harga_total', p_row->'harga_total', 'dp', p_row->'dp', 'total_dibayar', p_row->'total_dibayar', 'jatuh_tempo_kpr', p_row->'jatuh_tempo_kpr', 'reminder_kpr_dates', p_row->'reminder_kpr_dates', 'tenor_bulan', p_row->'tenor_bulan', 'keterangan_kpr', p_row->'keterangan_kpr', 'created_at', p_row->'created_at', 'updated_at', p_row->'updated_at')
        WHEN 'payments' THEN jsonb_build_object('id', p_row->'id', 'assignment_id', p_row->'assignment_id', 'jumlah_bayar', p_row->'jumlah_bayar', 'tanggal_bayar', p_row->'tanggal_bayar', 'catatan', p_row->'catatan', 'bukti_pembayaran', p_row->'bukti_pembayaran', 'is_auto_inject', p_row->'is_auto_inject', 'created_by', p_row->'created_by', 'created_at', p_row->'created_at')
        ELSE '{}'::jsonb
    END;
END;
$$;

CREATE OR REPLACE FUNCTION public.sync_enqueue_event()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    entity_name text := TG_ARGV[0];
    old_row jsonb := CASE WHEN TG_OP <> 'INSERT' THEN to_jsonb(OLD) ELSE NULL END;
    new_row jsonb := CASE WHEN TG_OP <> 'DELETE' THEN to_jsonb(NEW) ELSE NULL END;
    event_row jsonb;
    event_operation text;
    old_customer boolean := COALESCE(old_row->>'role', '') = 'customer';
    new_customer boolean := COALESCE(new_row->>'role', '') = 'customer';
BEGIN
    IF entity_name = 'customers' AND NOT old_customer AND NOT new_customer THEN
        IF TG_OP = 'DELETE' THEN RETURN OLD; ELSE RETURN NEW; END IF;
    END IF;

    IF TG_OP = 'DELETE' THEN
        event_operation := 'delete';
        event_row := old_row;
    ELSIF TG_OP = 'INSERT' THEN
        event_operation := 'insert';
        event_row := new_row;
    ELSIF entity_name = 'customers' AND old_customer AND NOT new_customer THEN
        event_operation := 'delete';
        event_row := old_row;
    ELSIF entity_name = 'customers' AND NOT old_customer AND new_customer THEN
        event_operation := 'insert';
        event_row := new_row;
    ELSE
        event_operation := 'update';
        event_row := new_row;
    END IF;

    INSERT INTO public.sync_outbox (entity, entity_id, operation, occurred_at, payload)
    VALUES (entity_name, (event_row->>'id')::uuid, event_operation, clock_timestamp(), public.sync_business_payload(entity_name, event_row));

    IF TG_OP = 'DELETE' THEN RETURN OLD; ELSE RETURN NEW; END IF;
END;
$$;

DO $$
DECLARE
    item record;
BEGIN
    FOR item IN SELECT * FROM (VALUES
        ('companies', 'companies'),
        ('projects', 'projects'),
        ('clusters', 'clusters'),
        ('units', 'units'),
        ('users', 'customers'),
        ('property_assignments', 'assignments'),
        ('payment_history', 'payments')
    ) AS mapping(table_name, entity_name)
    LOOP
        IF to_regclass('public.' || item.table_name) IS NOT NULL THEN
            EXECUTE format('DROP TRIGGER IF EXISTS %I ON public.%I', 'sync_bump_version_' || item.table_name, item.table_name);
            EXECUTE format('CREATE TRIGGER %I BEFORE INSERT OR UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.sync_bump_version()', 'sync_bump_version_' || item.table_name, item.table_name);
            EXECUTE format('DROP TRIGGER IF EXISTS %I ON public.%I', 'sync_enqueue_' || item.table_name, item.table_name);
            EXECUTE format('CREATE TRIGGER %I AFTER INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.sync_enqueue_event(%L)', 'sync_enqueue_' || item.table_name, item.table_name, item.entity_name);
        END IF;
    END LOOP;
END;
$$;
